language: go
go:
- 1.12.x
services:
- docker
env:
  global:
    secure: B9VpCyRSAAlvWYeqyX0CKLHX6KC4qO5PE1jSwRk0HWdhqhqAV2LLG9XbfltNI6zKRMAKQrSe3piwbComA3DYb2W1XKHhWGG4K4aJmSxSdjFsaRRVoSJe7/znHTVHvdTX+YbEaVO6O7zOm5xYPD5X2Hh3Fo8dSvyABJmhLhQKPdiXovKtU+DtbGLtUF1Y3LiZo9Oa/1BtCc3jsO3MkKb96jvEli3zNCbL16l3FMktjkd6IDlc3q+77kdSn14OikEFXzDDmlOcY1g+tKu0sclSIr6YGFI3Zo5NKMku3mhJfVCF1qyzylkgXpHqNlNHACucSo6hHkf4mYe1phE9GYUHWbW2ftKE2MnARMgjaW9RCKBd11TVa/GkHWBNxaiBLdEChVY1jJRR0Mo/sFZyBqNkeFAv2k426NBuz47ENXp7KKUZWY0sCxCEcgByyKR7E0HsPAkDvybftQKKDbuux0RwphzFN38Eux+OdEQNo0ze0QB8jumNQcwAI63bDdG+J+R/WYDLw9bXRiQbxgqvmxAjAoRPRE45C7QhPbU8I1kWWbOXwoHVLM7IFXM7Cjd17aSAEPzHkVGtsHtCtG9QwY6skV4xhZqwdMG4VygB+BlRu4UmWFLZ43815U9zpROWkW5b2xAEMbG6hGT6As1UDBm8k4AP/WomImS4WE6TwWEM37E=
jobs:
  include:
  - stage: test
    name: Run Go tests
    script:
    - make test
deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash
  skip_cleanup: true
  on:
    tags: true
